### ISSUE TITLE
Error when trying to execute with no arguments

### ISSUE THREAD

**Issue by StryxZilla** [htoyryla/convis#1]
I am getting the below error.  Any immediate thoughts?  (I am a novice with lua)

stryx@Andy-Ubuntu:~/neural-style$ th convis.lua
/home/stryx/torch/install/bin/luajit: convis.lua:5: unexpected symbol near '<'
stack traceback:
    [C]: in function 'dofile'
    ...tryx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

**Comment by StryxZilla** [comment]
Nevermind I'm an idiot and figured it out.  My lua file was corrupted.

**Comment by htoyryla** [comment]
Sounds like you downloaded the web page and not the raw file, has happened to me as well :)
